Build system update
Signed-off-by: dubo-dubon-duponey <dubodubonduponey+github@pm.me>

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -29,25 +29,55 @@ jobs:
       # XXX update this to a more recent apt proxy
       - name: Start apt proxy
         run: |
+          # Hiding the read-only token base64 to avoid github disabling it...
+          echo OWMyMGVhYzk4N2NhYWQxYmI3MzhmNTZkODNmOGMwOGJjZjlhNDc4YQo= | base64 -d | docker login ghcr.io -u dubo-dubon-duponey --password-stdin
           mkdir -p "$GITHUB_WORKSPACE/cache/apt"
+          mkdir -p "$GITHUB_WORKSPACE/cache/certs"
           chmod a+rwx "$GITHUB_WORKSPACE/cache/apt"
-          docker run --rm -d --pull always \
-            --name apt-cache \
+          chmod a+rwx "$GITHUB_WORKSPACE/cache/certs"
+          docker run --rm -d --expose 4443 --expose 8080 --pull always \
+            --name apt-front \
             --read-only \
             --cap-drop=ALL \
-            --expose 3142 \
-            --volume $GITHUB_WORKSPACE/cache/apt:/data \
-              dubodubonduponey/aptutil:buster-2020-08-01
+            --env TLS_AUTO=ignore_loaded_certs \
+            --env TLS=internal \
+            --env IS_PROXY=true \
+            --env DOMAIN=apt-front.local \
+            --cap-add=CAP_NET_BIND_SERVICE \
+            --user root \
+            --env PORT=443 \
+            --env PORT_HTTP=80 \
+            --env ADDITIONAL_DOMAINS=*.debian.org \
+            --volume "$GITHUB_WORKSPACE/cache/certs":/certs \
+            ghcr.io/dubo-dubon-duponey/aptutil:bullseye-2021-08-01
 
       - name: test
         run: |
-          # Hiding the read-only token base64 to avoid github disabling it...
-          echo OWMyMGVhYzk4N2NhYWQxYmI3MzhmNTZkODNmOGMwOGJjZjlhNDc4YQo= | base64 -d | docker login ghcr.io -u dubo-dubon-duponey --password-stdin
+          # Start buildkit
+          bkaddr="$(./hack/helpers/start-buildkit.sh)"
           # Set the path
-          export BIN_LOCATION="."
-          PATH="$BIN_LOCATION:$PATH"
+          export BIN_LOCATION="$(pwd)"
+          ./hack/helpers/install-tools.sh
+          export PATH="$BIN_LOCATION:$PATH"
           cd "$GITHUB_WORKSPACE"
+          # Sanity check
+          echo "Sanity checks"
+          command -v "cue" > /dev/null || {
+            echo "Cue installation had failed"
+            exit 1
+          }
+          command -v "buildctl" > /dev/null || {
+            echo "Cue installation had failed"
+            exit 1
+          }
+          buildctl --addr "$bkaddr" debug workers
+          docker logs --tail 200 apt-front
           # Lint
           ./hack/lint.sh
           # Test, with our injected proxy and environment
-          ./hack/test.sh --inject apt_proxy="http://$(docker inspect apt-cache | jq -rc .[0].NetworkSettings.Networks.bridge.IPAddress):3142" ".github/workflows/environment.cue"
+          #  --inject apt_proxy="http://$(docker inspect apt-front | jq -rc .[0].NetworkSettings.Networks.bridge.IPAddress):4443"
+          ./hack/test.sh \
+            --inject bk="$bkaddr" \
+            --inject ip="$(docker inspect apt-front | jq -rc .[0].NetworkSettings.Networks.bridge.IPAddress)" \
+            --inject trust="$(sudo cat "$GITHUB_WORKSPACE/cache/certs/pki/authorities/local/root.crt")" \
+            ".github/workflows/environment.cue"
